version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    environment:
      - PYTHON_BIN=python3
      - MONGO_URI=mongodb://mongodb:27017/EduStream
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  mongo-data:

